export const menus = [
  {
    parent: 'pageNav.workspace.workloads.deployments-detail',
    name: 'metrics-server',
    icon: 'SmcDuotone',
    clusterModule: 'metrics-server',
    title: 'hpa.title',
    order: 5,
    actionType: 'modal',
    actionValue: 'pageNav://pageNav.workspace.workloads.deployments-detail.metrics-server',
  },
  {
    parent: 'pageNav.workspace.workloads.statefulsets-detail',
    name: 'metrics-server',
    icon: 'SmcDuotone',
    clusterModule: 'metrics-server',
    title: 'hpa.title',
    order: 5,
    actionType: 'modal',
    actionValue: 'pageNav://pageNav.workspace.workloads.statefulsets-detail.metrics-server',
  },
  {
    parent: 'pageNav.cluster.deployments.detail',
    name: 'metrics-server',
    icon: 'SmcDuotone',
    ksModule: 'metrics-server',
    clusterModule: 'metrics-server',
    title: 'hpa.title',
    action: 'edit',
    order: 5,
    actionType: 'modal',
    actionValue: 'pageNav://pageNav.workspace.workloads.deployments-detail.metrics-server',
  },
  {
    parent: 'pageNav.cluster.statefulsets.detail',
    name: 'metrics-server',
    icon: 'SmcDuotone',
    clusterModule: 'metrics-server',
    title: 'hpa.title',
    action: 'edit',
    order: 5,
    actionType: 'modal',
    actionValue: 'pageNav://pageNav.workspace.workloads.statefulsets-detail.metrics-server',
  },
  {
    parent: 'workspace.app-workloads',
    name: 'hpa-list',
    title: 'hpa.title',
    order: 0,
    authKey: 'metrics-server',
  },
  {
    parent: 'cluster.app-workloads',
    name: 'hpa-list',
    title: 'hpa.title',
    order: 0,
    authKey: 'metrics-server',
  },
];
