export const menus = [
  {
    parent: 'pageNav.workspace.workloads.deployments-detail',
    name: 'metrics-server',
    title: 'hpa.title',
    order: 5,
    actionType: 'modal',
    actionValue: 'pageNav://pageNav.workspace.workloads.deployments-detail.metrics-server',
  },
  {
    parent: 'pageNav.workspace.workloads.statefulsets-detail',
    name: 'metrics-server',
    title: 'hpa.title',
    order: 5,
    actionType: 'modal',
    actionValue: 'pageNav://pageNav.workspace.workloads.statefulsets-detail.metrics-server',
  },
  {
    parent: 'pageNav.cluster.deployments.detail',
    name: 'metrics-server',
    title: 'hpa.title',
    action: 'edit',
    order: 5,
    actionType: 'modal',
    actionValue: 'pageNav://pageNav.cluster.deployments.detail.metrics-server',
  },
  {
    parent: 'pageNav.cluster.statefulsets.detail',
    name: 'metrics-server',
    title: 'hpa.title',
    action: 'edit',
    order: 5,
    actionType: 'modal',
    actionValue: 'pageNav://pageNav.cluster.statefulsets.detail.metrics-server',
  },
  {
    parent: 'cluster',
    name: 'elastic_scaling',
    title: 'hpa.menu.parent.title',
    icon: 'stretch',
    order: 4,
    skipIfExist: true,
  },
  {
    parent: 'workspace',
    name: 'elastic_scaling',
    title: 'hpa.menu.parent.title',
    icon: 'stretch',
    order: 2,
    skipIfExist: true,
    skipWorkspaceAuth: true,
  },
  {
    parent: 'workspace.elastic_scaling',
    name: 'hpa-list',
    title: 'hpa.title',
    workspaceModule: 'metrics-server',
  },
  {
    parent: 'cluster.elastic_scaling',
    name: 'hpa-list',
    title: 'hpa.title',
    clusterModule: 'metrics-server',
  },
];
